### ISSUE TITLE
TODO: version 1.0.0

### ISSUE THREAD

**Issue by erming** [erming/inputhistory#1]
- [x] Add `$.inputhistory.defaultOptions`
- [ ] Documentation on gh-pages

And when 1.0.0 is released:
- [ ] Add to [cdnjs](http://cdnjs.com/)
- [ ] Add to jquery.plugins
